version: 0.2

phases:
    build:
      commands:
        - cd ..
        - git clone https://$GIT_TOKEN:x-oauth-basic@github.com/XclaimInc/xclaim-api.git
        - git clone https://$GIT_TOKEN:x-oauth-basic@@github.com/XclaimInc/xclaim-web.git
        - ls
        # - docker-compose up -d
        # - export CI=true
        # - gem install coveralls-lcov
        # - echo "hello world"
        # - bundle install
        # - ruby test.rb
        # - coveralls-lcov --repo-token $COVERALLS_REPO_TOKEN coverage/lcov.info