version: 0.2

phases:
    build:
      commands:
        - export CI=true
        - gem install coveralls-lcov
        - echo "hello world"
        - bundle install
        - coveralls-lcov --repo-token $COVERALLS_REPO_TOKEN coverage/lcov.info