version: "3"
services:
  postgres:
    image: postgres:10.8
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres
      - POSTGRES_DB: postgres
    ports:
      - 5432:5432
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis
    ports:
        - 6379:6379
    entrypoint: "redis-server"