name: Testing github actions

on:
  push: 
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: mv docker-compose-e2e.yml ..
      - name: setting up
        working-directory: ../
        run: ls