name: Testing github actions

on:
  push: 
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: mv docker-compose-e2e.yml ..
      - name: setting up
        working-directory: ../
        run: ls
      - env: 
          GIT_TOKEN: ${{secrets.GIT_TOKEN}}
        working-directory: ../
        run: git clone https://$GIT_TOKEN:x-oauth-basic@github.com/XclaimInc/xclaim-api.git
      - env: 
          GIT_TOKEN: ${{secrets.GIT_TOKEN}}
        working-directory: ../
        run: git clone https://$GIT_TOKEN:x-oauth-basic@github.com/XclaimInc/xclaim-web.git
      - working-directory: ../
        run: mv docker-compose-e2e.yml xclaim-api/
      - working-directory: xclaim-api/
        run: docker-compose -f docker-compose-e2e.yml build